language: php

php:
  - 5.5
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database filmap_testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit